export const USER_ROLE = ["Admin", "User"] as const;

export const USER_SKILLS = [
  "Teaching",
  "Event Planning",
  "First Aid",
  "Photography",
  "Web Development",
  "Public Speaking",
  "Graphic Design",
  "Social Media Management",
  "Content Creation",
  "Data Analysis",
  "Project Management",
  "Marketing",
  "Research",
  "Writing",
  "Translation",
  "Video Editing",
  "Customer Service",
  "Sales",
  "Business Analysis",
  "Networking",
  "Data Entry",
  "Customer Support",
  "Strategic Planning",
  "Team Leadership",
  "Problem Solving",
] as const;

export const USER_CAUSES = [
  "Education",
  "Environment",
  "Animal Welfare",
  "Homelessness",
  "Healthcare",
  "Disaster Relief",
  "Human Rights",
  "Arts and Culture",
  "Community Development",
  "Youth Development",
  "Elderly Care",
  "Mental Health",
  "Disability Support",
  "Food Security",
] as const;
