import { type Metadata } from "next";

import { HeroUiProvider } from "@handson/ui/providers";
import "@handson/ui/styles";

import { geistMono, inter } from "@/config/font";

import { AuthProvider, TanstackQueryProvider } from "@/contexts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "HandsOn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistMono.variable} antialiased`}>
        <HeroUiProvider>
          <TanstackQueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </TanstackQueryProvider>
        </HeroUiProvider>
      </body>
    </html>
  );
}
